version: '3.8'

services:
  dss:
    image: ${GROUP_ID}/dss:${SERVICE_VERSION:-latest}
    hostname: dss
    container_name: dss
    depends_on:
      - zookeeper
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - kafdrop
    ports:
      - "8081:8081"
    volumes:
      - "./docker-logs:/workspace/dss/logs"
    user: root
    environment:
      - "SERVER_PORT=8081"
    networks:
      - ${GLOBAL_NETWORK:-services}

  api:
    image: ${GROUP_ID}/api:${SERVICE_VERSION:-latest}
    hostname: api
    container_name: api
    depends_on:
      - zookeeper
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - kafdrop
      - dss
    ports:
      - "8082:8082"
    volumes:
      - "./docker-logs:/workspace/api/logs"
    user: root
    environment:
      - "SERVER_PORT=8082"
    networks:
      - ${GLOBAL_NETWORK:-services}
