version: '3.8'

networks:
  back-tier:
    driver: bridge

services:
  redis-master-sentinel:
    build:
      context: ./redis
    hostname: redis-master-sentinel
    container_name: redis-master-sentinel
    restart: always
    ports:
      - "6379"
    volumes:
      - "./conf/master.conf:/opt/bitnami/redis/mounted-etc/redis.conf"
      - "./redis-master-sentinel:/bitnami/redis/data"
      - "./.log_redis-master-sentinel:/var/log/redis"
    user: root
    environment:
      - "REDIS_REPLICATION_MODE=master"
      - "REDIS_PASSWORD=julianraziffigaro"
    sysctls:
      - "net.ipv4.tcp_max_syn_backlog=65535"
      - "net.core.somaxconn=65535"
    networks:
      - back-tier

  redis-slave1-sentinel:
    build:
      context: ./redis
    hostname: redis-slave1-sentinel
    container_name: redis-slave1-sentinel
    restart: always
    depends_on:
      - redis-master-sentinel
    ports:
      - "6379"
    volumes:
      - "./conf/slave.conf:/opt/bitnami/redis/mounted-etc/redis.conf"
      - "./redis-slave1-sentinel:/bitnami/redis/data"
      - "./.log_redis-slave1-sentinel:/var/log/redis"
    user: root
    environment:
      - "REDIS_REPLICATION_MODE=slave"
      - "REDIS_MASTER_HOST=redis-master-sentinel"
      - "REDIS_MASTER_PASSWORD=julianraziffigaro"
      - "REDIS_PASSWORD=julianraziffigaro"
    sysctls:
      - "net.ipv4.tcp_max_syn_backlog=65535"
      - "net.core.somaxconn=65535"
    networks:
      - back-tier

  redis-slave2-sentinel:
    build:
      context: ./redis
    hostname: redis-slave2-sentinel
    container_name: redis-slave2-sentinel
    restart: always
    depends_on:
      - redis-master-sentinel
    ports:
      - "6379"
    volumes:
      - "./conf/slave.conf:/opt/bitnami/redis/mounted-etc/redis.conf"
      - "./redis-slave2-sentinel:/bitnami/redis/data"
      - "./.log_redis-slave2-sentinel:/var/log/redis"
    user: root
    environment:
      - "REDIS_REPLICATION_MODE=slave"
      - "REDIS_MASTER_HOST=redis-master-sentinel"
      - "REDIS_MASTER_PASSWORD=julianraziffigaro"
      - "REDIS_PASSWORD=julianraziffigaro"
    sysctls:
      - "net.ipv4.tcp_max_syn_backlog=65535"
      - "net.core.somaxconn=65535"
    networks:
      - back-tier