version: '3.8'

services:
  redis-master-sentinel:
    build:
      context: ./redis
    hostname: redis-master-sentinel
    container_name: redis-master-sentinel
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./conf/master.conf:/opt/bitnami/redis/mounted-etc/redis.conf"
      - "./redis-master-sentinel:/bitnami/redis/data"
      - "./.log_redis-master-sentinel:/var/log/redis"
    user: root
    environment:
      - "REDIS_REPLICATION_MODE=master"
      - "REDIS_PASSWORD=julianraziffigaro"
    sysctls:
      - "net.ipv4.tcp_max_syn_backlog=65535"
      - "net.core.somaxconn=65535"
    networks:
      - ${GLOBAL_NETWORK:-redis_sentinel}

  redis-slave1-sentinel:
    build:
      context: ./redis
    hostname: redis-slave1-sentinel
    container_name: redis-slave1-sentinel
    restart: always
    depends_on:
      - redis-master-sentinel
    ports:
      - "6380:6379"
    volumes:
      - "./conf/slave.conf:/opt/bitnami/redis/mounted-etc/redis.conf"
      - "./redis-slave1-sentinel:/bitnami/redis/data"
      - "./.log_redis-slave1-sentinel:/var/log/redis"
    user: root
    environment:
      - "REDIS_REPLICATION_MODE=slave"
      - "REDIS_MASTER_HOST=redis-master-sentinel"
      - "REDIS_MASTER_PASSWORD=julianraziffigaro"
      - "REDIS_PASSWORD=julianraziffigaro"
    sysctls:
      - "net.ipv4.tcp_max_syn_backlog=65535"
      - "net.core.somaxconn=65535"
    networks:
      - ${GLOBAL_NETWORK:-redis_sentinel}

  redis-slave2-sentinel:
    build:
      context: ./redis
    hostname: redis-slave2-sentinel
    container_name: redis-slave2-sentinel
    restart: always
    depends_on:
      - redis-master-sentinel
    ports:
      - "6381:6379"
    volumes:
      - "./conf/slave.conf:/opt/bitnami/redis/mounted-etc/redis.conf"
      - "./redis-slave2-sentinel:/bitnami/redis/data"
      - "./.log_redis-slave2-sentinel:/var/log/redis"
    user: root
    environment:
      - "REDIS_REPLICATION_MODE=slave"
      - "REDIS_MASTER_HOST=redis-master-sentinel"
      - "REDIS_MASTER_PASSWORD=julianraziffigaro"
      - "REDIS_PASSWORD=julianraziffigaro"
    sysctls:
      - "net.ipv4.tcp_max_syn_backlog=65535"
      - "net.core.somaxconn=65535"
    networks:
      - ${GLOBAL_NETWORK:-redis_sentinel}

  redis-sentinel1:
    build:
      context: ./sentinel
    hostname: redis-sentinel1
    container_name: redis-sentinel1
    restart: always
    depends_on:
      - redis-master-sentinel
      - redis-slave1-sentinel
      - redis-slave2-sentinel
    ports:
      - "26379:26379"
    user: root
    environment:
      - "REDIS_MASTER_HOST=redis-master-sentinel"
      - "REDIS_MASTER_PORT_NUMBER=6379"
      - "REDIS_MASTER_SET=mymaster"
      - "REDIS_SENTINEL_PORT_NUMBER=26379"
      - "REDIS_MASTER_PASSWORD=julianraziffigaro"
      - "REDIS_SENTINEL_QUORUM=2"
      - "REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=200"
      - "REDIS_SENTINEL_FAILOVER_TIMEOUT=500"
    sysctls:
      - "net.ipv4.tcp_max_syn_backlog=65535"
      - "net.core.somaxconn=65535"
    networks:
      - ${GLOBAL_NETWORK:-redis_sentinel}

  redis-sentinel2:
    build:
      context: ./sentinel
    hostname: redis-sentinel2
    container_name: redis-sentinel2
    restart: always
    depends_on:
      - redis-master-sentinel
      - redis-slave1-sentinel
      - redis-slave2-sentinel
    ports:
      - "26380:26379"
    user: root
    environment:
      - "REDIS_MASTER_HOST=redis-master-sentinel"
      - "REDIS_MASTER_PORT_NUMBER=6379"
      - "REDIS_MASTER_SET=mymaster"
      - "REDIS_SENTINEL_PORT_NUMBER=26379"
      - "REDIS_MASTER_PASSWORD=julianraziffigaro"
      - "REDIS_SENTINEL_QUORUM=2"
      - "REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=200"
      - "REDIS_SENTINEL_FAILOVER_TIMEOUT=500"
    sysctls:
      - "net.ipv4.tcp_max_syn_backlog=65535"
      - "net.core.somaxconn=65535"
    networks:
      - ${GLOBAL_NETWORK:-redis_sentinel}

  redis-sentinel3:
    build:
      context: ./sentinel
    hostname: redis-sentinel3
    container_name: redis-sentinel3
    restart: always
    depends_on:
      - redis-master-sentinel
      - redis-slave1-sentinel
      - redis-slave2-sentinel
    ports:
      - "26381:26379"
    user: root
    environment:
      - "REDIS_MASTER_HOST=redis-master-sentinel"
      - "REDIS_MASTER_PORT_NUMBER=6379"
      - "REDIS_MASTER_SET=mymaster"
      - "REDIS_SENTINEL_PORT_NUMBER=26379"
      - "REDIS_MASTER_PASSWORD=julianraziffigaro"
      - "REDIS_SENTINEL_QUORUM=2"
      - "REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=200"
      - "REDIS_SENTINEL_FAILOVER_TIMEOUT=500"
    sysctls:
      - "net.ipv4.tcp_max_syn_backlog=65535"
      - "net.core.somaxconn=65535"
    networks:
      - ${GLOBAL_NETWORK:-redis_sentinel}