version: '3.8'

services:
  dss:
    image: ${GROUP_ID}/dss:${SERVICE_VERSION:-latest}
    hostname: dss
    container_name: dss
    ports:
      - "8081:8081"
    user: root
    environment:
      - "SERVER_PORT=8081"
    networks:
      - ${GLOBAL_NETWORK:-services}

  api:
    image: ${GROUP_ID}/api:${SERVICE_VERSION:-latest}
    hostname: api
    container_name: api
    ports:
      - "8082:8082"
    user: root
    environment:
      - "SERVER_PORT=8082"
    networks:
      - ${GLOBAL_NETWORK:-services}
